#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TomsMonkeysMVVM.Droid.Resource", IsApplication=true)]

namespace TomsMonkeysMVVM.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::TomsMonkeysMVVM.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::TomsMonkeysMVVM.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxBind = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxDropDownItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxGroupItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxLang = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxSource = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplate = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplateSelector = global::TomsMonkeysMVVM.Droid.Resource.Attribute.MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollEnabled = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fastScrollEnabled;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollHorizontalThumbDrawable = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fastScrollHorizontalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollHorizontalTrackDrawable = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fastScrollHorizontalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollVerticalThumbDrawable = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fastScrollVerticalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fastScrollVerticalTrackDrawable = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fastScrollVerticalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.font = global::TomsMonkeysMVVM.Droid.Resource.Attribute.font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderAuthority = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontProviderAuthority;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderCerts = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontProviderCerts;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderFetchStrategy = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderFetchTimeout = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderPackage = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontProviderPackage;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontProviderQuery = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontProviderQuery;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontStyle = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.fontWeight = global::TomsMonkeysMVVM.Droid.Resource.Attribute.fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layoutManager = global::TomsMonkeysMVVM.Droid.Resource.Attribute.layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.reverseLayout = global::TomsMonkeysMVVM.Droid.Resource.Attribute.reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.spanCount = global::TomsMonkeysMVVM.Droid.Resource.Attribute.spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.stackFromEnd = global::TomsMonkeysMVVM.Droid.Resource.Attribute.stackFromEnd;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.notification_action_color_filter = global::TomsMonkeysMVVM.Droid.Resource.Color.notification_action_color_filter;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.notification_icon_bg_color = global::TomsMonkeysMVVM.Droid.Resource.Color.notification_icon_bg_color;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.ripple_material_light = global::TomsMonkeysMVVM.Droid.Resource.Color.ripple_material_light;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Color.secondary_text_default_material_light = global::TomsMonkeysMVVM.Droid.Resource.Color.secondary_text_default_material_light;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_inset_horizontal_material = global::TomsMonkeysMVVM.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_inset_vertical_material = global::TomsMonkeysMVVM.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_padding_horizontal_material = global::TomsMonkeysMVVM.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_button_padding_vertical_material = global::TomsMonkeysMVVM.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.compat_control_corner_material = global::TomsMonkeysMVVM.Droid.Resource.Dimension.compat_control_corner_material;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_default_thickness = global::TomsMonkeysMVVM.Droid.Resource.Dimension.fastscroll_default_thickness;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_margin = global::TomsMonkeysMVVM.Droid.Resource.Dimension.fastscroll_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.fastscroll_minimum_range = global::TomsMonkeysMVVM.Droid.Resource.Dimension.fastscroll_minimum_range;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::TomsMonkeysMVVM.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::TomsMonkeysMVVM.Droid.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::TomsMonkeysMVVM.Droid.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_action_icon_size = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_action_icon_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_action_text_size = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_action_text_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_big_circle_margin = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_big_circle_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_content_margin_start = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_content_margin_start;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_large_icon_height = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_large_icon_height;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_large_icon_width = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_large_icon_width;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_main_column_padding_top = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_media_narrow_margin = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_right_icon_size = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_right_icon_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_right_side_padding_top = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_small_icon_background_padding = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_small_icon_size_as_large = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_subtext_size = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_subtext_size;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_top_pad = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_top_pad;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.notification_top_pad_large_text = global::TomsMonkeysMVVM.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_action_background = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_action_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_bg_low;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low_normal = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_bg_low_normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_low_pressed = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_normal = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_bg_normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_bg_normal_pressed = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_icon_background = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_icon_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_template_icon_bg = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_template_icon_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_template_icon_low_bg = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notification_tile_bg = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notification_tile_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Drawable.notify_panel_notification_icon_bg = global::TomsMonkeysMVVM.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvvmCrossTagId = global::TomsMonkeysMVVM.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvxBindingTagUnique = global::TomsMonkeysMVVM.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_container = global::TomsMonkeysMVVM.Droid.Resource.Id.action_container;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_divider = global::TomsMonkeysMVVM.Droid.Resource.Id.action_divider;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_image = global::TomsMonkeysMVVM.Droid.Resource.Id.action_image;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.action_text = global::TomsMonkeysMVVM.Droid.Resource.Id.action_text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.actions = global::TomsMonkeysMVVM.Droid.Resource.Id.actions;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.async = global::TomsMonkeysMVVM.Droid.Resource.Id.async;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.blocking = global::TomsMonkeysMVVM.Droid.Resource.Id.blocking;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.chronometer = global::TomsMonkeysMVVM.Droid.Resource.Id.chronometer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.forever = global::TomsMonkeysMVVM.Droid.Resource.Id.forever;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.icon = global::TomsMonkeysMVVM.Droid.Resource.Id.icon;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.icon_group = global::TomsMonkeysMVVM.Droid.Resource.Id.icon_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.info = global::TomsMonkeysMVVM.Droid.Resource.Id.info;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.italic = global::TomsMonkeysMVVM.Droid.Resource.Id.italic;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::TomsMonkeysMVVM.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.line1 = global::TomsMonkeysMVVM.Droid.Resource.Id.line1;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.line3 = global::TomsMonkeysMVVM.Droid.Resource.Id.line3;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.normal = global::TomsMonkeysMVVM.Droid.Resource.Id.normal;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_background = global::TomsMonkeysMVVM.Droid.Resource.Id.notification_background;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_main_column = global::TomsMonkeysMVVM.Droid.Resource.Id.notification_main_column;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.notification_main_column_container = global::TomsMonkeysMVVM.Droid.Resource.Id.notification_main_column_container;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.right_icon = global::TomsMonkeysMVVM.Droid.Resource.Id.right_icon;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.right_side = global::TomsMonkeysMVVM.Droid.Resource.Id.right_side;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.tag_transition_group = global::TomsMonkeysMVVM.Droid.Resource.Id.tag_transition_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.text = global::TomsMonkeysMVVM.Droid.Resource.Id.text;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.text2 = global::TomsMonkeysMVVM.Droid.Resource.Id.text2;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.time = global::TomsMonkeysMVVM.Droid.Resource.Id.time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.title = global::TomsMonkeysMVVM.Droid.Resource.Id.title;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Integer.status_bar_notification_info_maxnum = global::TomsMonkeysMVVM.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_action = global::TomsMonkeysMVVM.Droid.Resource.Layout.notification_action;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_action_tombstone = global::TomsMonkeysMVVM.Droid.Resource.Layout.notification_action_tombstone;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_custom_big = global::TomsMonkeysMVVM.Droid.Resource.Layout.notification_template_custom_big;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_icon_group = global::TomsMonkeysMVVM.Droid.Resource.Layout.notification_template_icon_group;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_part_chronometer = global::TomsMonkeysMVVM.Droid.Resource.Layout.notification_template_part_chronometer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Layout.notification_template_part_time = global::TomsMonkeysMVVM.Droid.Resource.Layout.notification_template_part_time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.String.status_bar_notification_info_overflow = global::TomsMonkeysMVVM.Droid.Resource.String.status_bar_notification_info_overflow;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification = global::TomsMonkeysMVVM.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Info = global::TomsMonkeysMVVM.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::TomsMonkeysMVVM.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Time = global::TomsMonkeysMVVM.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.TextAppearance_Compat_Notification_Title = global::TomsMonkeysMVVM.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.Widget_Compat_NotificationActionContainer = global::TomsMonkeysMVVM.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Style.Widget_Compat_NotificationActionText = global::TomsMonkeysMVVM.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamily;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderAuthority = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderCerts = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderPackage = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamily_fontProviderQuery = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamilyFont;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_font = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_fontStyle = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_android_fontWeight = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_font = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamilyFont_font;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_fontStyle = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.FontFamilyFont_fontWeight = global::TomsMonkeysMVVM.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxBind = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxLang = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl_MvxTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView_MvxSource = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxItemTemplate = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxRecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector = global::TomsMonkeysMVVM.Droid.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_descendantFocusability = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollEnabled = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_fastScrollEnabled;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollHorizontalThumbDrawable = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_fastScrollHorizontalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollHorizontalTrackDrawable = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_fastScrollHorizontalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollVerticalThumbDrawable = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_fastScrollVerticalThumbDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_fastScrollVerticalTrackDrawable = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_fastScrollVerticalTrackDrawable;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_spanCount = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::TomsMonkeysMVVM.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001f
			public const int MvxBind = 2130771999;
			
			// aapt resource value: 0x7f010023
			public const int MvxDropDownItemTemplate = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int MvxGroupItemTemplate = 2130772004;
			
			// aapt resource value: 0x7f010022
			public const int MvxItemTemplate = 2130772002;
			
			// aapt resource value: 0x7f010020
			public const int MvxLang = 2130772000;
			
			// aapt resource value: 0x7f010025
			public const int MvxSource = 2130772005;
			
			// aapt resource value: 0x7f010021
			public const int MvxTemplate = 2130772001;
			
			// aapt resource value: 0x7f01001e
			public const int MvxTemplateSelector = 2130771998;
			
			// aapt resource value: 0x7f010012
			public const int alpha = 2130771986;
			
			// aapt resource value: 0x7f010009
			public const int coordinatorLayoutStyle = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int fastScrollEnabled = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fastScrollHorizontalThumbDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fastScrollHorizontalTrackDrawable = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int fastScrollVerticalThumbDrawable = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fastScrollVerticalTrackDrawable = 2130771974;
			
			// aapt resource value: 0x7f01001a
			public const int font = 2130771994;
			
			// aapt resource value: 0x7f010013
			public const int fontProviderAuthority = 2130771987;
			
			// aapt resource value: 0x7f010016
			public const int fontProviderCerts = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int fontProviderFetchStrategy = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int fontProviderFetchTimeout = 2130771992;
			
			// aapt resource value: 0x7f010014
			public const int fontProviderPackage = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int fontProviderQuery = 2130771989;
			
			// aapt resource value: 0x7f010019
			public const int fontStyle = 2130771993;
			
			// aapt resource value: 0x7f01001c
			public const int fontVariationSettings = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int fontWeight = 2130771995;
			
			// aapt resource value: 0x7f01000a
			public const int keylines = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int layout_anchor = 2130771981;
			
			// aapt resource value: 0x7f01000f
			public const int layout_anchorGravity = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int layout_behavior = 2130771980;
			
			// aapt resource value: 0x7f010011
			public const int layout_dodgeInsetEdges = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int layout_insetEdge = 2130771984;
			
			// aapt resource value: 0x7f01000e
			public const int layout_keyline = 2130771982;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int statusBarBackground = 2130771979;
			
			// aapt resource value: 0x7f01001d
			public const int ttcIndex = 2130771997;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080003
			public const int notification_action_color_filter = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int notification_icon_bg_color = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int notification_material_background_media_default_color = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int primary_text_default_material_dark = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int ripple_material_light = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int secondary_text_default_material_dark = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int secondary_text_default_material_light = 2131230726;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f05000e
			public const int compat_button_inset_horizontal_material = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int compat_button_inset_vertical_material = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int compat_button_padding_horizontal_material = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int compat_button_padding_vertical_material = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int compat_control_corner_material = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int compat_notification_large_icon_max_height = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int compat_notification_large_icon_max_width = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int fastscroll_default_thickness = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int fastscroll_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int fastscroll_minimum_range = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int item_touch_helper_swipe_escape_velocity = 2131034117;
			
			// aapt resource value: 0x7f050015
			public const int notification_action_icon_size = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int notification_action_text_size = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int notification_big_circle_margin = 2131034135;
			
			// aapt resource value: 0x7f05000b
			public const int notification_content_margin_start = 2131034123;
			
			// aapt resource value: 0x7f050018
			public const int notification_large_icon_height = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int notification_large_icon_width = 2131034137;
			
			// aapt resource value: 0x7f05000c
			public const int notification_main_column_padding_top = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int notification_media_narrow_margin = 2131034125;
			
			// aapt resource value: 0x7f05001a
			public const int notification_right_icon_size = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int notification_right_side_padding_top = 2131034122;
			
			// aapt resource value: 0x7f05001b
			public const int notification_small_icon_background_padding = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int notification_small_icon_size_as_large = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int notification_subtext_size = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int notification_top_pad = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int notification_top_pad_large_text = 2131034143;
			
			// aapt resource value: 0x7f050006
			public const int subtitle_corner_radius = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int subtitle_outline_width = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int subtitle_shadow_offset = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int subtitle_shadow_radius = 2131034121;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_low_bg = 2130837516;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int splash = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int MvvmCrossTagId = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int MvxBindingTagUnique = 2131099658;
			
			// aapt resource value: 0x7f06002c
			public const int action0 = 2131099692;
			
			// aapt resource value: 0x7f060029
			public const int action_container = 2131099689;
			
			// aapt resource value: 0x7f060030
			public const int action_divider = 2131099696;
			
			// aapt resource value: 0x7f06002a
			public const int action_image = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int action_text = 2131099691;
			
			// aapt resource value: 0x7f06003a
			public const int actions = 2131099706;
			
			// aapt resource value: 0x7f06001a
			public const int all = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int async = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int blocking = 2131099676;
			
			// aapt resource value: 0x7f06000b
			public const int bottom = 2131099659;
			
			// aapt resource value: 0x7f06002d
			public const int cancel_action = 2131099693;
			
			// aapt resource value: 0x7f06000c
			public const int center = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int center_horizontal = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int center_vertical = 2131099662;
			
			// aapt resource value: 0x7f060035
			public const int chronometer = 2131099701;
			
			// aapt resource value: 0x7f06000f
			public const int clip_horizontal = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int clip_vertical = 2131099664;
			
			// aapt resource value: 0x7f060023
			public const int countUp = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int countUpExecuteButton = 2131099684;
			
			// aapt resource value: 0x7f060011
			public const int end = 2131099665;
			
			// aapt resource value: 0x7f06003c
			public const int end_padder = 2131099708;
			
			// aapt resource value: 0x7f060012
			public const int fill = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int fill_horizontal = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int fill_vertical = 2131099668;
			
			// aapt resource value: 0x7f06001d
			public const int forever = 2131099677;
			
			// aapt resource value: 0x7f060025
			public const int gogoButton = 2131099685;
			
			// aapt resource value: 0x7f060037
			public const int icon = 2131099703;
			
			// aapt resource value: 0x7f06003b
			public const int icon_group = 2131099707;
			
			// aapt resource value: 0x7f060020
			public const int imageView = 2131099680;
			
			// aapt resource value: 0x7f060036
			public const int info = 2131099702;
			
			// aapt resource value: 0x7f06001e
			public const int italic = 2131099678;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060015
			public const int left = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int line1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int line3 = 2131099650;
			
			// aapt resource value: 0x7f06002f
			public const int media_actions = 2131099695;
			
			// aapt resource value: 0x7f060021
			public const int monkeyList = 2131099681;
			
			// aapt resource value: 0x7f060028
			public const int monkeyListItemCount = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int monkeyListItemName = 2131099687;
			
			// aapt resource value: 0x7f060019
			public const int none = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int normal = 2131099679;
			
			// aapt resource value: 0x7f060039
			public const int notification_background = 2131099705;
			
			// aapt resource value: 0x7f060032
			public const int notification_main_column = 2131099698;
			
			// aapt resource value: 0x7f060031
			public const int notification_main_column_container = 2131099697;
			
			// aapt resource value: 0x7f060016
			public const int right = 2131099670;
			
			// aapt resource value: 0x7f060038
			public const int right_icon = 2131099704;
			
			// aapt resource value: 0x7f060033
			public const int right_side = 2131099699;
			
			// aapt resource value: 0x7f060026
			public const int sexGroupe = 2131099686;
			
			// aapt resource value: 0x7f060017
			public const int start = 2131099671;
			
			// aapt resource value: 0x7f06002e
			public const int status_bar_latest_event_content = 2131099694;
			
			// aapt resource value: 0x7f060003
			public const int tag_transition_group = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int tag_unhandled_key_event_manager = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int tag_unhandled_key_listeners = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int text = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int text2 = 2131099655;
			
			// aapt resource value: 0x7f060034
			public const int time = 2131099700;
			
			// aapt resource value: 0x7f060008
			public const int title = 2131099656;
			
			// aapt resource value: 0x7f060018
			public const int top = 2131099672;
			
			// aapt resource value: 0x7f060022
			public const int tvSelectedPosition = 2131099682;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int cancel_button_image_alpha = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int status_bar_notification_info_maxnum = 2131296257;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int DetailView = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MainView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int monkey_list_item = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_action = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_action_tombstone = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_media_action = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_media_cancel_action = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_big_media = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_big_media_custom = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_big_media_narrow = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_big_media_narrow_custom = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int notification_template_custom_big = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_template_icon_group = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int notification_template_lines_media = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int notification_template_media = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int notification_template_media_custom = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int notification_template_part_chronometer = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int notification_template_part_time = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int sex_item = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int SplashScreen = 2130968595;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0002
			public const int app_name = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int hello = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_overflow = 2131361792;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public const int TextAppearance_Compat_Notification = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Info = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int TextAppearance_Compat_Notification_Line2 = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int TextAppearance_Compat_Notification_Media = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int TextAppearance_Compat_Notification_Time = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int TextAppearance_Compat_Notification_Title = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131165187;
			
			// aapt resource value: 0x7f07000d
			public const int Theme_Splash = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int Widget_Compat_NotificationActionContainer = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Widget_Compat_NotificationActionText = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int Widget_Support_CoordinatorLayout = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771986};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] CoordinatorLayout = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchor = 2;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 4;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_behavior = 1;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 6;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_keyline = 3;
			
			public static int[] FontFamily = new int[] {
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			public static int[] MvxBinding = new int[] {
					2130771999,
					2130772000};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130772001};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130772004};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772005};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130772002,
					2130772003};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] MvxRecyclerView = new int[] {
					2130771998};
			
			// aapt resource value: 0
			public const int MvxRecyclerView_MvxTemplateSelector = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
